# Site settings
title: cocook小站
SEOTitle: cocook小站 | panmg`s Blog
header-img: img/home-bg-hzw.jpg
email: panmingguang2004@gmail.com
description: "java, mysql, linux, postgresql, cocook小站, panmg's blogs, 潘明光的博客"
keyword: ""
url: "https://cocook.cn"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username:     panmingguang
zhihu_username:     pan-ming-guang
github_username:    panmingguang
codealiyun_username:  414072243/resume/blob/master/panminguang2019.md
#twitter_username:   huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: pmg

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-154848922-1'            # Format: UA-xxxxxx-xx
ga_domain: cocook.cn

# https://www.google.com/adsense/new/u/0/pub-3298061137690508/home 
ad-client: ca-pub-8025781494025163


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Every day is a chance to change lives <br> 每一天都是一个改变生活的机会"
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
   {
        title: "cnck每日頭條",
        href: "https://t.cn/A67PlMa1"
    },
     {
        title: "cocook全网影视搜",
        href: "https://search.cocook.cn/"
    },
     {
        title: "",
        href: "https://www.cncknews.com"
    }
]
